version: '3.8'

services:
  app:
    container_name: tactix-app
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    command: npm run start:dev

  worker:
    container_name: tactix-worker
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env
    command: node dist/queue/queue.worker.js

  redis:
    image: redis:7-alpine
    container_name: tactix-redis
    ports:
      - '6379:6379'
